### ISSUE TITLE
Not getting language or markup options

### ISSUE THREAD

**Issue by hermyt** [Leonard-The-Wise/NWScript-Npp#7]
I've done the plugin installation off both the plugin manager and attempted manual installation.

The plugin appears to install, compilation etc seems to work, I did the dialogs accepting administrative restart to put xml files in their appropriate location overrideMap.xml has a nwscript entry in it for language definition however nwscript doesn't show up in my language options.

I've just attempted updating npp as well and its currently on 8.4.8

![image](https://user-images.githubusercontent.com/4231773/214443281-e461f934-9fa7-4885-9136-054c63c90624.png)

and here's an image of the plugins menu

![image](https://user-images.githubusercontent.com/4231773/214445464-d4661540-f580-4d00-b5f7-5a7d8864e7da.png)

I've tried removal and reinstallation a few times but to no avail, only the language options seem to be missing, 

c:\program files(x86)\notepad++\plugins has NWScript-Npp folder inside of which is NWScript-Npp.dll and xml and functionlist and autocomplete folders which contain the nwscript.xml and overridemap.xml

in c:\program files(x86)\notepad++\functionlist nwscript.xml file exists as well as the overridemap.xml which has the 
<association id= "nwscript.xml"			langID="86"/>	
line in it

in c:\program files(x86)\notepad++\autocompletion there is also the nwscript.xml file

in %appdata%\roaming\notepad++\plugins\config is nwscript-npp.ini and xml and NWScript-Npp-EngineObjects.bin

Pretty stumped now, I don't know enough about lexer projects to know if there's a file out of place or why its not showing up in the language page, and as you can see from screenshots the nss files aren't being identified.

In addition if I go to compile an nss file I get a prompt:

![image](https://user-images.githubusercontent.com/4231773/214445068-1fb33ff4-4966-4720-bb4a-a7c3ca017851.png)

I can choose ok and the file appears to compile correctly just something seems off with the context and language aspect of the plugin.

**Comment by Leonard-The-Wise** [comment]
Checked on notepad++ 8.5.4, it works. Whatever the issue, try to update notepad++.
